# Test Rules
GTEST_LIB = -lgtest -lgtest_main -pthread
TEST_SRC = tests/player_test.cpp tests/map_test.cpp
TEST_OBJ = $(TEST_SRC:.cpp=.o)
TEST_TARGET = test

$(TEST_TARGET): $(TEST_OBJ) $(LIBS)
	$(CXX) $(CXXFLAGS) -o $(TEST_TARGET) $(TEST_OBJ) $(LIBS) $(GTEST_LIB)

test: $(TEST_TARGET)
	./$(TEST_TARGET)
